### ISSUE TITLE
How do I use pemtpm in intel tpm2.0-tss?

### ISSUE THREAD

**Issue by searchmawnag** [manoj23/pemtpm#1]
hello manoj23.

I using intel tpm2.0-tss.
I can't use this command "./pemtpm -ipem private.pem -opu opu.bin -opr opr.bin"
So, I changed your code to intel tpm2.0-tss. I got opu.bin, opr.bin.

TPM2 does not work when I run it in the following way.
  ./tpm2_createprimary -A e -g 0x000B -G 0x0001 -C po1.ctx
 ./tpm2_load -c po1.ctx -uopu.bin -r opr.bin -n key1.name -C obj1.ctx
 -> Load Object Failed ! ErrorCode: 0x1d5
 -> ./tpm2_rc_decode 0x1d5
       error layer
       hex: 0x0
       identifier: TSS2_TPM_ERROR_LEVEL
       description: Error produced by the TPM
       format 1 error code
       hex: 0x15
       identifier: TPM_RC_SIZE
       description: structure is the wrong size
       parameter
        hex: 0x100
        identifier:  TPM_RC_1
       description:  (null)

Help Me..

Thank you.

**Comment by sidalit** [comment]
@searchmawnag If you want to import your PEM key into your TPM, I suggest you to use the `importpem` tool from https://sourceforge.net/p/ibmtpm20tss/tss/ci/master/tree/
